server:
  port: 9000
  context-path: /ces

mybatis:
  mapperLocations: classpath*:mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cesdb?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000

rsgene:
  explosiveForceOrStamina: rs1815739,rs699,rs16892496,rs1042713,rs8192678,rs2267668,rs2016520,rs12722,rs1799945,rs1799722,rs1205
  injuryRecoveryAbility: rs1799865,rs13266634,rs2700352,rs28497577,rs1800629,rs4880,rs1815739
  injuryRisk: rs1800012,rs12722,rs591058,rs2276109,rs2073711,rs970547
  obesityRisk: rs5082,rs662799,rs1801282,rs1137101,rs9939609,rs1800588,rs429358
  
total-score: 
  explosiveForceScore: 4.0
  staminaScore: 18.0
  injuryRecoveryAbilityScore: 8.0
  injuryRiskScore: 5.0
  injuryRiskScore_female: 8.0
  obesityRiskScore: 5.0 
  fatReducingSensitivityScore: 7.0
  heartLungFunctionScore: 6.0
  energySupplyScore: 8.0